The `7-base_geometry` module
======================

Using `BaseGeometry`
-------------------

Import the function:
        >>> BaseGeometry = __import__("7-base_geometry").BaseGeometry


Test:
         >>> bg = BaseGeometry()
         >>> bg.area()
         Traceback (most recent call last):
         ...
         Exception: area() is not implemented

Test:
         >>> bg.integer_validator("width", True)
         Traceback (most recent call last):
         ...
         TypeError: width must be an integer

Test:
	 >>> bg = BaseGeometry()
	 >>> bg.integer_validator("width", "98")
	 Traceback (most recent call last):
	 ...
	 TypeError: width must be an integer

Test:
	 >>> bg = BaseGeometry()
	 >>> bg.integer_validator("name", 0)
	 Traceback (most recent call last):
	 ...
	 ValueError: name must be greater than 0

Test:
	 >>> bg.integer_validator("name", -1)
	 Traceback (most recent call last):
	 ...
	 ValueError: name must be greater than 0

Test:
	 >>> bg = BaseGeometry()
	 >>> bg.integer_validator("name", 5)


Test:
	 >>> bg.integer_validator("name")
	 Traceback (most recent call last):
	 ...
	 TypeError: integer_validator() missing 1 required positional argument: 'value'

Test:
	 >>> bg = BaseGeometry()
 	 >>> bg.integer_validator()
	 Traceback (most recent call last):
	 ...
	 TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test:
	 >>> bg.integer_validator("name", 6, 7)
	 Traceback (most recent call last):
 	 ...
	 TypeError: integer_validator() takes 3 positional arguments but 4 were given

Test:
	 >>> bg = BaseGeometry()
	 >>> bg.area(1)
	 Traceback (most recent call last):
	 ...
	 TypeError: area() takes 1 positional argument but 2 were given

Test:
	 >>> bg.area(1, 2)
	 Traceback (most recent call last):
	 ...
	 TypeError: area() takes 1 positional argument but 3 were given

Test:
	 >>> bg = BaseGeometry()
	 >>> bg.integer_validator("name", [2])
	 Traceback (most recent call last):
	 ...
	 TypeError: name must be an integer

Test:
         >>> bg.integer_validator("name", (4,5))
         Traceback (most recent call last):
         ...
         TypeError: name must be an integer

Test:
         >>> bg = BaseGeometry()
         >>> bg.integer_validator("name", {4, 5})
         Traceback (most recent call last):
         ...
         TypeError: name must be an integer

Test:
         >>> bg.integer_validator("name", None)
         Traceback (most recent call last):
         ...
         TypeError: name must be an integer
